Update Docker Compose config to pull from GitHub registry
motioneye-project/motioneye pull request #2482
Opened 2022-05-15 15:28 UTC by MichaIng

Signed-off-by: MichaIng <micha@dietpi.com>

2022-05-15 15:43 UTC, MarcelCoding requested changes
Maybe add a comment, that edge isn't a production version.

2022-05-15 15:53 UTC, MichaIng commented
Needs to be changed to stable (and Docker registry) once we have a release. I'll add it as ToDo.

2022-05-15 16:32 UTC, MarcelCoding approved these changes

2022-05-15 19:00 UTC, merged

2022-05-16 05:37 UTC, kleini reviewed
LGTM